import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Bell, Wifi, CheckCircle2, Smartphone, Settings } from "lucide-react";
export const ActivaSinQr = () => {
    return (_jsxs("div", { className: "space-y-10 animate-in fade-in duration-500", children: [_jsxs("div", { className: "text-center space-y-4", children: [_jsx(Badge, { className: "bg-yellow-400 text-yellow-950 font-black px-4 py-1 rounded-full uppercase text-[10px]", children: "Sin C\u00F3digo QR" }), _jsx("h2", { className: "text-4xl md:text-5xl font-black italic uppercase tracking-tighter text-[#002f6c]", children: "Activaci\u00F3n Directa" }), _jsx("p", { className: "text-slate-500 font-medium max-w-xl mx-auto italic", children: "Si ya solicitaste tu eSIM en CAC, act\u00EDvala mediante una notificaci\u00F3n push autom\u00E1tica." })] }), _jsx("div", { className: "grid md:grid-cols-3 gap-6", children: [
                    { icon: _jsx(Settings, {}), t: "1. Solicita tu eSIM", d: "En CAC Telcel, un asesor vinculará tu línea al equipo." },
                    { icon: _jsx(Wifi, {}), t: "2. Conéctate a WiFi", d: "Es indispensable para completar el proceso sin errores." },
                    { icon: _jsx(Bell, {}), t: "3. Acepta la notificación", d: "Sigue las instrucciones en pantalla al recibir el aviso." }
                ].map((item, i) => (_jsxs(Card, { className: "p-8 rounded-[2rem] border-none bg-white shadow-sm hover:shadow-md transition-all", children: [_jsx("div", { className: "w-12 h-12 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center mb-6", children: item.icon }), _jsx("h4", { className: "font-black italic uppercase text-slate-900 text-sm mb-2", children: item.t }), _jsx("p", { className: "text-xs text-slate-500 leading-relaxed", children: item.d })] }, i))) }), _jsxs("div", { className: "grid md:grid-cols-2 gap-8", children: [_jsxs(Card, { className: "p-8 rounded-[2.5rem] border-none bg-slate-900 text-white", children: [_jsxs("div", { className: "flex items-center gap-3 mb-6", children: [_jsx(Smartphone, { className: "text-blue-400" }), _jsx("h3", { className: "text-xl font-black italic uppercase", children: "Activaci\u00F3n en iOS" })] }), _jsx("div", { className: "space-y-4", children: [
                                    "Recibe la notificación: Toca el mensaje de 'eSIM Telcel lista'.",
                                    "Añade tu eSIM: Se abrirá el asistente. Toca 'Continuar'.",
                                    "Finaliza: Cuando aparezca la confirmación, toca 'Listo'."
                                ].map((step, i) => (_jsxs("div", { className: "flex gap-3 text-xs font-medium text-slate-300", children: [_jsx(CheckCircle2, { className: "w-4 h-4 text-emerald-500 shrink-0" }), " ", step] }, i))) })] }), _jsxs("div", { className: "flex flex-col justify-center items-center text-center p-8 bg-blue-50 rounded-[2.5rem] border border-blue-100", children: [_jsx(CheckCircle2, { className: "w-16 h-16 text-emerald-500 mb-4" }), _jsx("h3", { className: "text-2xl font-black italic uppercase text-[#002f6c] mb-2", children: "\u00A1eSIM Activa!" }), _jsxs("p", { className: "text-xs font-bold text-slate-600 leading-relaxed", children: ["Ahora disfruta tu l\u00EDnea con llamadas, mensajes y datos sin necesidad de chip f\u00EDsico.", _jsx("br", {}), _jsx("br", {}), _jsx("span", { className: "text-[10px] text-blue-400 italic", children: "Sigue aprovechando los beneficios Telcel." })] })] })] })] }));
};
